# Generated by Django 3.0.14 on 2021-04-25 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=200, verbose_name='Detalle')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'niveles',
                'db_table': 'niveles',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=200, verbose_name='Detalle')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'turnos',
                'db_table': 'turnos',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=4, verbose_name='Curso')),
                ('division', models.CharField(max_length=4, verbose_name='División')),
                ('detalle', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aula', to='tablas.Nivel')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aula', to='tablas.Turno')),
            ],
            options={
                'verbose_name_plural': 'aula',
                'db_table': 'aula',
                'unique_together': {('nivel', 'turno', 'curso', 'division')},
            },
        ),
    ]
