# Generated by Django 3.0.14 on 2021-04-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'verbose_name_plural': 'aulas'},
        ),
        migrations.AlterField(
            model_name='aula',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='tablas.Nivel'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='tablas.Turno'),
        ),
        migrations.AlterModelTable(
            name='aula',
            table='aulas',
        ),
    ]
